user_pref("browser.migration.version", 4);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.pinned", "[{\"title\":\"Яндекс\",\"url\":\"https://www.ya.ru/?from=dist_vz&win=582&clid=2313449-121\"},{\"title\":\"Яндекс Маркет\",\"url\":\"https://market.yandex.ru/?from=dist_vz&win=582&clid=2313450-121\"},{\"title\":\"auto.ru\",\"url\":\"https://auto.ru/?from=dist_vz&win=594&clid=2721059-43\"},{\"title\":\"Яндекс Недвижимость\",\"url\":\"https://realty.yandex.ru/?from=dist_vz&win=694&clid=9183505-887\"}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.search.defaultenginename", "Яндекс");
user_pref("browser.search.selectedEngine", "Яндекс");
user_pref("browser.search.suggest.enabled", true);
user_pref("browser.search.useDBForOrder", false);
user_pref("browser.startup.homepage", "https://www.ya.ru/?win=582&clid=2313439-121");
user_pref("extensions.sovetnik.yandex.statistics.clid.21", "2313451-121");
user_pref("extensions.sovetnik@metabar.ru.getAddons.cache.enabled", false);
user_pref("extensions.yasearch@yandex.ru.defender.homepage.protected", "https://www.ya.ru/?win=582&clid=2313439-121");
user_pref("yasearch.defence.homepage.protected", "https://www.ya.ru/?win=582&clid=2313439-121");
